import * as Knex from "knex";

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex("cards").del();

  // Inserts seed entries
  await knex("cards").insert([
    { value: "ACE", suit: "SPADES", code: "AS", short: true },
    { value: "2", suit: "SPADES", code: "2S", short: false },
    { value: "3", suit: "SPADES", code: "3S", short: false },
    { value: "4", suit: "SPADES", code: "4S", short: false },
    { value: "5", suit: "SPADES", code: "5S", short: false },
    { value: "6", suit: "SPADES", code: "6S", short: true },
    { value: "7", suit: "SPADES", code: "7S", short: true },
    { value: "8", suit: "SPADES", code: "8S", short: true },
    { value: "9", suit: "SPADES", code: "9S", short: true },
    { value: "10", suit: "SPADES", code: "10S", short: true },
    { value: "JACK", suit: "SPADES", code: "JS", short: true },
    { value: "QUEEN", suit: "SPADES", code: "QS", short: true },
    { value: "KING", suit: "SPADES", code: "KS", short: true },
    { value: "ACE", suit: "CLUBS", code: "AC", short: true },
    { value: "2", suit: "CLUBS", code: "2C", short: false },
    { value: "3", suit: "CLUBS", code: "3C", short: false },
    { value: "4", suit: "CLUBS", code: "4C", short: false },
    { value: "5", suit: "CLUBS", code: "5C", short: false },
    { value: "6", suit: "CLUBS", code: "6C", short: true },
    { value: "7", suit: "CLUBS", code: "7C", short: true },
    { value: "8", suit: "CLUBS", code: "8C", short: true },
    { value: "9", suit: "CLUBS", code: "9C", short: true },
    { value: "10", suit: "CLUBS", code: "10C", short: true },
    { value: "JACK", suit: "CLUBS", code: "JC", short: true },
    { value: "QUEEN", suit: "CLUBS", code: "QC", short: true },
    { value: "KING", suit: "CLUBS", code: "KC", short: true },
    { value: "ACE", suit: "DIAMONDS", code: "AD", short: true },
    { value: "2", suit: "DIAMONDS", code: "2D", short: false },
    { value: "3", suit: "DIAMONDS", code: "3D", short: false },
    { value: "4", suit: "DIAMONDS", code: "4D", short: false },
    { value: "5", suit: "DIAMONDS", code: "5D", short: false },
    { value: "6", suit: "DIAMONDS", code: "6D", short: true },
    { value: "7", suit: "DIAMONDS", code: "7D", short: true },
    { value: "8", suit: "DIAMONDS", code: "8D", short: true },
    { value: "9", suit: "DIAMONDS", code: "9D", short: true },
    { value: "10", suit: "DIAMONDS", code: "10D", short: true },
    { value: "JACK", suit: "DIAMONDS", code: "JD", short: true },
    { value: "QUEEN", suit: "DIAMONDS", code: "QD", short: true },
    { value: "KING", suit: "DIAMONDS", code: "KD", short: true },
    { value: "ACE", suit: "HEARTS", code: "AH", short: true },
    { value: "2", suit: "HEARTS", code: "2H", short: false },
    { value: "3", suit: "HEARTS", code: "3H", short: false },
    { value: "4", suit: "HEARTS", code: "4H", short: false },
    { value: "5", suit: "HEARTS", code: "5H", short: false },
    { value: "6", suit: "HEARTS", code: "6H", short: true },
    { value: "7", suit: "HEARTS", code: "7H", short: true },
    { value: "8", suit: "HEARTS", code: "8H", short: true },
    { value: "9", suit: "HEARTS", code: "9H", short: true },
    { value: "10", suit: "HEARTS", code: "10H", short: true },
    { value: "JACK", suit: "HEARTS", code: "JH", short: true },
    { value: "QUEEN", suit: "HEARTS", code: "QH", short: true },
    { value: "KING", suit: "HEARTS", code: "KH", short: true },
  ]);
}
